title: Kemal Enver
description: Lead Software Engineer from the UK.   I have seven years experience writing iPhone & iPad applications for major brands and clients.
twitter: kemalenver
email: kemal@kemalenver.com
github: kemalenver
show_downloads: false
google_analytics:
theme: 
