theme: jekyll-theme-minimal

title: Kemal Enver
description: Portfolio and Projects
show_downloads: true
google_analytics: "SomeTrackingID"

email: kemal@kemalenver.com
twitter_username: kemalenver
github_username:  kemalenverf
