theme: jekyll-theme-minimal

title: Kemal Enver
description: Portfolio and Projects
* Stuff
* List

show_downloads: false
google_analytics: "SomeTrackingID"

email: kemal@kemalenver.com
twitter_username: kemalenver
github_username:  kemalenverf
