title: Kemal Enver
description: Lead Software Engineer from the UK with experience writing iOS applications for 9 years since iOS 2.   I have written iPhone & iPad applications for major brands and clients that have won awards, been featured by Apple and been top of their categories.
twitter: kemalenver
email: kemal@kemalenver.com
github: kemalenver
show_downloads: false
google_analytics:
baseurl: /website
theme:
