title: Kemal Enver
description: I'm a Lead Software Engineer from the UK who's been writing iOS applications for nine years, starting with iOS 2. I have written iPhone & iPad applications for major brands that have won awards, been featured by Apple and have topped their categories on the App Store. These apps are currently being used by millions of people worldwide.
twitter: kemalenver
email: kemal@kemalenver.com
github: kemalenver
linkedin: https://www.linkedin.com/in/kemal-enver-50587036/
show_downloads: false
google_analytics:
baseurl:
theme:
