title: Kemal Enver
description: I'm currently Head of Mobile Engineering at Domain Australia. I've been working with mobile in some form since 2007, and have written and ran teams that have created iOS, Apple TV, Android, Windows Phone, Blackberry, and Mac applications for major brands - many of them have won awards, been featured, and been top of their category. I've also worked on some open source projects - the most popular of which is Planetary.  My apps are currently being used by millions of people worldwide.
twitter: kemalenver
email: kemal@kemalenver.com
github: kemalenver
linkedin: https://www.linkedin.com/in/kemal-enver-50587036/
blog: https://www.occlusion.io
show_downloads: false
google_analytics:
baseurl:
theme:
